language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --verbose --stderr --configuration tests/phpunit.xml.dist